version: "3.3"

services:
   elasticsearch:
      image: nagarindkx/elasticsearch-noxpack
      volumes:
        - elasticsearch-volume:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - elk
   kibana:
      image: nagarindkx/kibana-noxpack
      environment:
        - "XPACK_MONITORING_ENABLED: false"
      ports:
        - 5601:5601
      networks:
        - elk
   logstash:
      image: nagarindkx/logstash-noxpack
      environment:
        - "XPACK_MONITORING_ENABLED: false"
      volumes:
        - logstash-volume:/usr/share/logstash/data
      ports:
        - 10514:5514
      networks:
        - elk

networks:
   elk:
      driver: overlay

volumes:
   elasticsearch-volume:
   logstash-volume:
