version: "3.3"

services:
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
# Add by command
      command: elasticsearch -Expack.security.enabled=false
      ports:
        - 9200:9200
      networks:
        - elk
   kibana:
      image: docker.elastic.co/kibana/kibana:5.5.0
#      environment:
#        - "ELASTICSEARCH_USERNAME: elastic"
#        - "ELASTICSEARCH_PASSWORD: changeme"
      ports:
        - 5601:5601
      networks:
        - elk
   logstash:
      image: docker.elastic.co/logstash/logstash:5.5.0
      networks:
        - elk

networks:
   elk:
      driver: overlay
