version: "3.3"

services:
   elasticsearch:
      image: nagarindkx/elasticsearch-noxpack
      ports:
        - 9200:9200
      networks:
        - elk
   kibana:
      image: nagarindkx/kibana-noxpack
      environment:
        - "elasticsearch.username: "
        - "elasticsearch.password: "
      ports:
        - 5601:5601
      networks:
        - elk
   logstash:
      image: logstash
      environment:
        - "ELASTICSEARCH_HOST: elasticsearch"
        - "ELASTICSEARCH_PORT: 9200"
      volumes:
        - $(pwd)/logstash/conf.d/:/etc/logstash/conf.d
      ports:
        - 10514:10514
      networks:
        - elk

networks:
   elk:
      driver: overlay
