version: "3.3"

services:
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
      command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
      networks:
        - elk
   kibana:
      image: docker.elastic.co/kibana/kibana:5.5.0
      networks:
        - elk
   logstash:
      image: docker.elastic.co/logstash/logstash:5.5.0
      networks:
        - elk

networks:
   elk:
      driver: overlay
