version: "3.3"

services:
   elasticsearch:
      image: nagarindkx/elasticsearch-noxpack
      ports:
        - 9200:9200
      networks:
        - elk
   kibana:
      image: nagarindkx/kibana-noxpack
      ports:
        - 5601:5601
      networks:
        - elk
   logstash:
      image: nagarindkx/logstash-noxpack
      networks:
        - elk

networks:
   elk:
      driver: overlay
