version: "3.3"

services:
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
      ports:
        - 9200:9200
   kibana:
      image: docker.elastic.co/kibana/kibana:5.5.0
      ports:
        - 5601:5601
   logstash:
      image: docker.elastic.co/logstash/logstash:5.5.0
